# Jekyll & GitHub Pages 사이트의 기본 설정 파일입니다.
# --- 사이트 기본 정보 --- #
# 이 부분을 자신의 정보에 맞게 수정해주세요.
title: 나의 탄소발자국 계산기           # 사이트의 제목 (예: 홍길동의 기술 블로그)
description: "나의 오늘이 배출한 탄소량과 1일 적정 탄소 배출량을 직접 확인해보세요!" # 검색 엔진에 표시될 사이트 설명
url: "https://yongwoo1207.github.io"  # ⚠️ 매우 중요: "YOUR-USERNAME"을 본인의 깃허브 아이디로 바꾸세요.
baseurl: "/carbonFootPrint_cal"       # ⚠️ 프로젝트 페이지인 경우 "/REPOSITORY-NAME" 형식으로 입력하세요. (아래 설명 참고)

# --- 빌드 설정 --- #
# 사이트의 기술적인 부분을 설정합니다.
theme: minima                # 사이트의 디자인 테마. 'minima'는 가장 기본적인 테마입니다.
plugins:
  - jekyll-feed
  - jekyll-sitemap          # 사이트맵 자동 생성을 위한 플러그인 (이전 답변과 관련)

# 필요한 경우 이 아래에 다른 설정을 추가할 수 있습니다.
